name = "annyeong-app"

main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"
route = "annyeong.app/*"

[site]
  bucket = "./public"

[build]
  command = "npm run build"
